name: Build and publish PDF

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      #- name: Build with latexmk
      #  uses: xu-cheng/latex-action@v2
      #  with:
      #    root_file: main.tex
      #    latexmk_use_xelatex: true

      - name: Publish
        run: |
          mkdir latex.out/
          touch latex.out/main.pdf
          mv latex.out/main.pdf apunte.pdf
          git checkout --orphan build
          git reset
          git add apunte.pdf
          git commit -m "Latest build"
          git push origin build
