name: Build and publish PDF

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build with latexmk
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Publish
        run: |
          cp latex.out/main.pdf apunte.pdf
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git checkout --orphan build
          git reset
          git add apunte.pdf
          git commit -m "Latest build"
          git push --force origin build
